CREATE TABLE IF NOT EXISTS PRICES (
    HASH VARCHAR PRIMARY KEY,
    SOURCE VARCHAR,
    DATE VARCHAR,
    UNIT VARCHAR,
    PAGEURL VARCHAR,
    PRICEAVG DOUBLE,
    PRICEMAX DOUBLE,
    PRICEMIN DOUBLE,
    PRODUCT VARCHAR
) WITH (
    kafka_topic='prices',
    value_format='json',
    partitions=1
);
